### ISSUE TITLE
Feature: Build Silicon with Github Action

### ISSUE THREAD

**Issue by minthemiddle** [minthemiddle/Quick-Capture#20]
Right now, I have to manually build on Mac Silicone.
And add to the release downloads.

Spike whether this can be automated via Github Action.

**Comment by minthemiddle** [comment]
Some ideas:
https://github.com/tauri-apps/tauri/discussions/6090

**Comment by minthemiddle** [comment]
Some idea on how to tweak based on this:

```
name: 'publish'

# This will trigger the action on each push to the `release` branch.
on:
  push:
    tags:
      - 'v*'

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-20.04, windows-latest]
        include:
          - platform: macos-latest
            target: universal-apple-darwin
          - platform: macos-latest
            target: x86_64-apple-darwin
          - platform: macos-latest
            target: aarch64-apple-darwin
          - platform: ubuntu-20.04
            target: ''
          - platform: windows-latest
            target: x86_64-pc-windows-msvc
          - platform: windows-latest
            target: i686-pc-windows-msvc

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-apple-darwin

      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-20.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf

      - name: install frontend dependencies
        run: yarn install # change this to npm or pnpm depending on which one you use

      - name: build CSS
        run: npx tailwindcss -i src/in.css -o src/out.css --minify

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: v__VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version
          releaseName: 'v__VERSION__'
          releaseBody: 'See the assets to download this version and install.'
          releaseDraft: true
          prerelease: false
          args: ${{ matrix.target != '' && '--target ${{ matrix.target }}' || '' }} 
```
